# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 192.168.0.115
  become: yes

  tasks:

- name: Call Roles
  hosts: 192.168.0.115
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   #- motd
   - copy
